import type { Assumptions, Employee, Investment, SubProject, PipelineOpportunity, MonthlyResult, Scenario } from './types';

export const defaultAssumptions: Assumptions = {
  id: 'default',
  name: 'Pressupostos Gambit Labs',
  // Labor
  employerSocialSecurityRate: 0.2375,
  employeeSocialSecurityRate: 0.11,
  monthsPaidPerYear: 14,
  monthlyMealAllowance: 167.07,
  monthlyToolsCostPerEmployee: 100,
  monthlyInsuranceCostPerEmployee: 30,
  averageEquipmentCost: 1500,
  monthlyOtherCostsPerEmployee: 50,
  // Commercial
  averageProjectTicket: 15000,
  averageMonthlyRecurringRevenue: 1800,
  leadToMeetingConversion: 0.20,
  meetingToProposalConversion: 0.60,
  proposalToCloseConversion: 0.25,
  averageSaleCycleDays: 60,
  oneOffRevenueShare: 0.70,
  recurringRevenueShare: 0.30,
  // Financial
  grossMargin: 0.50,
  targetNetMargin: 0.20,
  vatRate: 0.23,
  corporateTaxRate: 0.21,
  baseInterestRate: 0.035,
  spread: 0.02,
  discountRate: 0.10,
  inflation: 0.025,
  annualGrowthRate: 0.20,
  defaultCommissionRate: 0.05,
  // Operational
  deliveryCapacityPerPerson: 25000,
  salesCapacityPerPerson: 80000,
  avgProjectsPerManager: 8,
  monthlyFixedCosts: 5000,
  annualRevenueGoal: 5000000,
};

export const mockEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Business Developer Sénior',
    role: 'Business Developer Sénior',
    department: 'commercial',
    grossMonthlySalary: 3700,
    monthlyToolsCost: 120,
    monthlyOtherCosts: 100,
    monthlyMealAllowance: 167.07,
    annualBonus: 5000,
    initialEquipmentCost: 2000,
    trainingCost: 1000,
    variableCommission: 5,
    expectedMonthlyRevenue: 80000,
    status: 'planned',
    startDate: '2024-01-01',
    notes: 'Responsável pelo desenvolvimento de negócio e gestão de key accounts.',
    maritalStatus: 'single',
    dependents: 0,
    hiringModel: 'revenue_based',
    monthlyBillableCapacity: 0,
    ajudasCustoDiasPerMonth: 0,
    ajudasCustoTipo: 'none',
    ajudasCustoValorDiaCustom: 0,
    ajudasKmPerMonth: 0,
    ajudasKmRateCustom: 0,
    ajudasKmVehicle: 'car',
  },
  {
    id: 'emp-2',
    name: 'SDR / Apoio Comercial',
    role: 'Sales Development Representative',
    department: 'commercial',
    grossMonthlySalary: 1500,
    monthlyToolsCost: 80,
    monthlyOtherCosts: 50,
    monthlyMealAllowance: 167.07,
    annualBonus: 1500,
    initialEquipmentCost: 1200,
    trainingCost: 500,
    variableCommission: 3,
    expectedMonthlyRevenue: 40000,
    status: 'planned',
    startDate: '2024-01-01',
    notes: 'Prospeção, qualificação de leads e apoio ao Business Developer.',
    maritalStatus: 'single',
    dependents: 0,
    hiringModel: 'revenue_based',
    monthlyBillableCapacity: 0,
    ajudasCustoDiasPerMonth: 0,
    ajudasCustoTipo: 'none',
    ajudasCustoValorDiaCustom: 0,
    ajudasKmPerMonth: 0,
    ajudasKmRateCustom: 0,
    ajudasKmVehicle: 'car',
  },
  {
    id: 'emp-3',
    name: 'Técnico Delivery / Operacional',
    role: 'Técnico de Implementação',
    department: 'delivery',
    grossMonthlySalary: 1500,
    monthlyToolsCost: 100,
    monthlyOtherCosts: 50,
    monthlyMealAllowance: 167.07,
    annualBonus: 1000,
    initialEquipmentCost: 1500,
    trainingCost: 800,
    variableCommission: 0,
    expectedMonthlyRevenue: 25000,
    status: 'planned',
    startDate: '2024-02-01',
    notes: 'Entrega de projetos e suporte a clientes.',
    maritalStatus: 'single',
    dependents: 0,
    hiringModel: 'capacity_based',
    monthlyBillableCapacity: 20000,
    ajudasCustoDiasPerMonth: 0,
    ajudasCustoTipo: 'none',
    ajudasCustoValorDiaCustom: 0,
    ajudasKmPerMonth: 0,
    ajudasKmRateCustom: 0,
    ajudasKmVehicle: 'car',
  },
];

export const mockInvestments: Investment[] = [
  {
    id: 'inv-1',
    name: 'Expansão Comercial Gambit Labs',
    category: 'team',
    description: 'Contratação de equipa comercial e de delivery para suportar crescimento para 5M€/ano',
    initialInvestment: 85000,
    subsidyAmount: 0,
    financedAmount: 30000,
    ownCapital: 55000,
    expectedMonthlyRevenue: 150000,
    expectedMonthlySavings: 0,
    monthlyOperatingCosts: 12000,
    startDate: '2024-01-01',
    durationMonths: 36,
    riskLevel: 'medium',
    status: 'approved',
    notes: 'Investimento principal para escalar a empresa de serviços.',
  },
];

export const mockSubProjects: SubProject[] = [
  {
    id: 'sp-1',
    investmentId: 'inv-1',
    name: 'Contratação Business Developer',
    category: 'team',
    initialCost: 3700,
    monthlyCost: 5800,
    expectedMonthlyRevenue: 80000,
    expectedMonthlySavings: 0,
    owner: 'CEO',
    startDate: '2024-01-01',
    endDate: '2026-12-31',
    executionPercentage: 100,
    status: 'in_progress',
    notes: 'Contratado em Janeiro 2024',
  },
  {
    id: 'sp-2',
    investmentId: 'inv-1',
    name: 'Contratação SDR',
    category: 'team',
    initialCost: 1700,
    monthlyCost: 2400,
    expectedMonthlyRevenue: 40000,
    expectedMonthlySavings: 0,
    owner: 'Business Developer',
    startDate: '2024-01-01',
    endDate: '2026-12-31',
    executionPercentage: 100,
    status: 'in_progress',
    notes: 'Contratado em Janeiro 2024',
  },
  {
    id: 'sp-3',
    investmentId: 'inv-1',
    name: 'Contratação Técnico Delivery',
    category: 'team',
    initialCost: 2300,
    monthlyCost: 2500,
    expectedMonthlyRevenue: 25000,
    expectedMonthlySavings: 0,
    owner: 'COO',
    startDate: '2024-02-01',
    endDate: '2026-12-31',
    executionPercentage: 100,
    status: 'in_progress',
    notes: 'Contratado em Fevereiro 2024',
  },
  {
    id: 'sp-4',
    investmentId: 'inv-1',
    name: 'CRM Comercial (Onestop)',
    category: 'technology',
    initialCost: 5000,
    monthlyCost: 200,
    expectedMonthlyRevenue: 0,
    expectedMonthlySavings: 2000,
    owner: 'Business Developer',
    startDate: '2024-01-15',
    endDate: '2024-03-31',
    executionPercentage: 100,
    status: 'completed',
    notes: 'CRM desenvolvido internamente pela equipa Gambit',
  },
  {
    id: 'sp-5',
    investmentId: 'inv-1',
    name: 'Website Comercial',
    category: 'marketing',
    initialCost: 4500,
    monthlyCost: 100,
    expectedMonthlyRevenue: 0,
    expectedMonthlySavings: 500,
    owner: 'Marketing',
    startDate: '2024-02-01',
    endDate: '2024-04-30',
    executionPercentage: 100,
    status: 'completed',
    notes: 'Website redesenhado com foco em conversão',
  },
  {
    id: 'sp-6',
    investmentId: 'inv-1',
    name: 'Automação de Propostas',
    category: 'technology',
    initialCost: 3000,
    monthlyCost: 150,
    expectedMonthlyRevenue: 0,
    expectedMonthlySavings: 1500,
    owner: 'Business Developer',
    startDate: '2024-03-01',
    endDate: '2024-05-31',
    executionPercentage: 75,
    status: 'in_progress',
    notes: 'Automação do processo de criação e envio de propostas',
  },
  {
    id: 'sp-7',
    investmentId: 'inv-1',
    name: 'Campanha LinkedIn Ads',
    category: 'marketing',
    initialCost: 5000,
    monthlyCost: 2000,
    expectedMonthlyRevenue: 20000,
    expectedMonthlySavings: 0,
    owner: 'Marketing',
    startDate: '2024-02-01',
    endDate: '2024-12-31',
    executionPercentage: 50,
    status: 'in_progress',
    notes: 'Campanhas de geração de leads no LinkedIn',
  },
  {
    id: 'sp-8',
    investmentId: 'inv-1',
    name: 'Sistema de Reporting',
    category: 'technology',
    initialCost: 2000,
    monthlyCost: 100,
    expectedMonthlyRevenue: 0,
    expectedMonthlySavings: 800,
    owner: 'COO',
    startDate: '2024-04-01',
    endDate: '2024-06-30',
    executionPercentage: 20,
    status: 'planned',
    notes: 'Dashboard de reporting para gestão interna',
  },
];

export const mockPipeline: PipelineOpportunity[] = [
  {
    id: 'pip-1',
    clientName: 'Empresa Alpha, Lda',
    opportunityName: 'Sistema de Automação de Processos',
    service: 'Automação & IA',
    estimatedValue: 45000,
    probability: 75,
    expectedCloseDate: '2024-02-15',
    responsible: 'Business Developer',
    stage: 'proposal_sent',
    nextAction: 'Follow-up proposta',
    source: 'referral',
    notes: 'Cliente referenciado por parceiro. Grande interesse.',
    createdAt: '2024-01-10',
  },
  {
    id: 'pip-2',
    clientName: 'Beta Solutions SA',
    opportunityName: 'CRM Customizado',
    service: 'Desenvolvimento Software',
    estimatedValue: 28000,
    probability: 50,
    expectedCloseDate: '2024-03-01',
    responsible: 'Business Developer',
    stage: 'negotiation',
    nextAction: 'Reunião final de negociação',
    source: 'linkedin',
    notes: 'Em fase de negociação de preço e âmbito.',
    createdAt: '2024-01-05',
  },
  {
    id: 'pip-3',
    clientName: 'Gamma Corp',
    opportunityName: 'Consultoria Transformação Digital',
    service: 'Consultoria',
    estimatedValue: 60000,
    probability: 30,
    expectedCloseDate: '2024-04-30',
    responsible: 'Business Developer',
    stage: 'diagnosis_done',
    nextAction: 'Preparar proposta detalhada',
    source: 'inbound',
    notes: 'Empresa grande, ciclo longo mas grande potencial.',
    createdAt: '2024-01-20',
  },
  {
    id: 'pip-4',
    clientName: 'Delta Tech',
    opportunityName: 'App Mobile Interna',
    service: 'Desenvolvimento Software',
    estimatedValue: 18000,
    probability: 60,
    expectedCloseDate: '2024-02-28',
    responsible: 'SDR',
    stage: 'proposal_sent',
    nextAction: 'Aguardar decisão',
    source: 'outbound',
    notes: 'PME com orçamento definido.',
    createdAt: '2024-01-15',
  },
  {
    id: 'pip-5',
    clientName: 'Epsilon Group',
    opportunityName: 'Retainer Mensal - Suporte TI',
    service: 'Suporte & Manutenção',
    estimatedValue: 2400,
    probability: 80,
    expectedCloseDate: '2024-02-10',
    responsible: 'Business Developer',
    stage: 'negotiation',
    nextAction: 'Assinar contrato',
    source: 'referral',
    notes: 'Contrato recorrente mensal. Quase fechado.',
    createdAt: '2024-01-22',
  },
  {
    id: 'pip-6',
    clientName: 'Zeta Industries',
    opportunityName: 'Migração para Cloud',
    service: 'Cloud & Infraestrutura',
    estimatedValue: 35000,
    probability: 25,
    expectedCloseDate: '2024-05-31',
    responsible: 'SDR',
    stage: 'meeting_scheduled',
    nextAction: 'Reunião de diagnóstico',
    source: 'event',
    notes: 'Contacto feito em evento de networking.',
    createdAt: '2024-01-28',
  },
];

function generateMonthlyResults(): MonthlyResult[] {
  const results: MonthlyResult[] = [];
  const months = ['2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06'];
  const plannedMonthly = 5000000 / 12;

  const actuals = [0.72, 0.85, 0.91, 0.88, 0.95, 1.02];

  months.forEach((month, i) => {
    const actual = plannedMonthly * actuals[i];
    const costs = actual * 0.55;
    results.push({
      id: `mr-${i + 1}`,
      month,
      plannedRevenue: plannedMonthly,
      actualRevenue: Math.round(actual),
      recurringRevenue: Math.round(actual * 0.3),
      oneOffRevenue: Math.round(actual * 0.7),
      actualCosts: Math.round(costs),
      salaries: Math.round(costs * 0.6),
      marketing: Math.round(costs * 0.1),
      software: Math.round(costs * 0.05),
      otherCosts: Math.round(costs * 0.25),
      investmentExecuted: i < 2 ? 15000 : 3000,
      newClients: Math.round(3 + Math.random() * 3),
      proposalsSent: Math.round(8 + Math.random() * 5),
      meetingsHeld: Math.round(15 + Math.random() * 8),
      leadsGenerated: Math.round(30 + Math.random() * 20),
      projectsClosed: Math.round(2 + Math.random() * 3),
      churn: Math.round(Math.random() * 2),
      cashReceived: Math.round(actual * 0.85),
      overdueCash: Math.round(actual * 0.15),
    });
  });

  return results;
}

export const mockMonthlyResults: MonthlyResult[] = generateMonthlyResults();

export const mockScenarios: Scenario[] = [
  {
    id: 'sc-1',
    name: 'Conservador',
    type: 'conservative',
    color: '#6366f1',
    assumptionsOverride: {
      annualRevenueGoal: 2500000,
      grossMargin: 0.45,
      targetNetMargin: 0.15,
      proposalToCloseConversion: 0.20,
      averageProjectTicket: 12000,
    },
    notes: 'Crescimento orgânico com equipa mínima. Baixo risco.',
  },
  {
    id: 'sc-2',
    name: 'Base',
    type: 'base',
    color: '#0ea5e9',
    assumptionsOverride: {
      annualRevenueGoal: 5000000,
      grossMargin: 0.50,
      targetNetMargin: 0.20,
    },
    notes: 'Cenário mais provável com execução consistente do plano.',
  },
  {
    id: 'sc-3',
    name: 'Agressivo',
    type: 'aggressive',
    color: '#10b981',
    assumptionsOverride: {
      annualRevenueGoal: 8000000,
      grossMargin: 0.55,
      targetNetMargin: 0.22,
      proposalToCloseConversion: 0.30,
      averageProjectTicket: 20000,
    },
    notes: 'Execução perfeita, mercado favorável e equipa de alto desempenho.',
  },
];
